# Generated by Django 3.2.8 on 2021-11-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_testserializer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestSerializer',
        ),
    ]
